common: &common
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: <%= ENV['POSTGRESQL_DATABASE']%>
  pool: 50
  username: <%= ENV['POSTGRESQL_USERNAME']%>
  password: <%= ENV['POSTGRESQL_PASSWORD']%>
  host: <%= ENV['POSTGRESQL_ADDRESS']%>
  port: 5432

development:
  <<: *common

test:
  <<: *common
  database: capu_api_test

production:
  <<: *common